---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 63d2776f4ec9f717e8cc292a3e2593d742584d79
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/git-branch: main
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=interview-core&var-version=1.0.0-SNAPSHOT
      fabric8.io/scm-tag: HEAD
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/interview/interview-core
    labels:
      app: interview-core
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: gubee
    name: interview-core
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: interview-core
      provider: fabric8
      group: gubee
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 63d2776f4ec9f717e8cc292a3e2593d742584d79
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=interview-core&var-version=1.0.0-SNAPSHOT
          fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/interview/interview-core
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/git-branch: main
          fabric8.io/scm-tag: HEAD
        labels:
          app: interview-core
          provider: fabric8
          version: 1.0.0-SNAPSHOT
          group: gubee
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: gubee/interview
          imagePullPolicy: IfNotPresent
          name: interview-api
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
